name: jtech_anime_base
description: jtech anime base
version: 0.0.1
homepage: https://github.com/WuXuBaiYang/jtech_anime

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # 国际化(ALL)
  intl: ^0.18.1

  # 路径(ALL)
  path: ^1.8.3

  # 路径管理(NO WEB)
  path_provider: ^2.1.1

  # sp缓存(ALL)
  shared_preferences: ^2.2.1

  # 加密(ALL)
  crypto: ^3.0.3

  # 日志(ALL)
  logger: ^2.0.2

  # 网络请求(ALL)
  dio: ^5.3.2

  # 图片(ALL)
  extended_image: ^8.1.0

  # 图标(ALL)
  font_awesome_flutter: ^10.5.0

  # 数据库(ALL-NO WEB)
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1

  # 包信息(ALL)
  package_info_plus: ^4.1.0

  # 动画(ALL)
  lottie: ^2.6.0

  # 模糊(ALL)
  blur: ^3.1.0

  # 跑马灯(ALL)
  text_scroll: ^0.2.0

  # 刷新组件(ALL)
  easy_refresh: ^3.3.2+1

  # 视频播放器(ALL)
  media_kit: ^1.1.7
  media_kit_video: ^1.1.8
  media_kit_libs_video: ^1.0.1

  # hls文件解析(ALL)
  flutter_hls_parser: ^2.0.1

  # ffmpeg(NO WEB)
  ffmpeg_helper: ^1.0.1

  # 后台下载器(NO WEB)
  background_downloader: ^7.9.4

  # js运行时(NO WEB)
  flutter_js: ^0.8.0

  # br解压缩(ALL)
  brotli: ^0.6.0

  # html解析方法(ALL)
  html: ^0.15.4

  # 图片选择器(ALL)
  image_picker: ^1.0.4

  # 音量控制(NO WEB)
  flutter_volume_controller: ^1.2.7

  # 集合操作(ALL)
  collection: ^1.17.2

  # url跳转(ALL)
  url_launcher: ^6.1.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

  # 数据库框架生成器
  isar_generator: ^3.1.0+1

  # 构建器
  build_runner: any

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/source/
    - assets/anime/
#
# For details regarding assets in packages, see
# https://flutter.dev/assets-and-images/#from-packages
#
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware

# To add custom fonts to your package, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts in packages, see
# https://flutter.dev/custom-fonts/#from-packages
